-- Small local learning dataset for the first two project tables.
-- This is intentionally smaller than the complete production ERP schema.

WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SUYOG;

CREATE TABLE SC_APPLICATION_USERS (
    USER_NO        VARCHAR2(30) NOT NULL,
    COMPANY_CODE   VARCHAR2(30) NOT NULL,
    LOGIN_CODE     VARCHAR2(30) NOT NULL,
    LOGIN_EDESC    VARCHAR2(100),
    PASSWORD       VARCHAR2(100) NOT NULL,
    CREATED_BY     VARCHAR2(30),
    CREATED_DATE   DATE DEFAULT SYSDATE,
    DELETED_FLAG   CHAR(1) DEFAULT 'N',
    CONSTRAINT PK_SC_APPLICATION_USERS PRIMARY KEY (USER_NO, COMPANY_CODE),
    CONSTRAINT UK_SC_APPLICATION_USERS_LOGIN UNIQUE (COMPANY_CODE, LOGIN_CODE)
);

CREATE TABLE IP_ITEM_MASTER_SETUP (
    COMPANY_CODE    VARCHAR2(30)  NOT NULL,
    ITEM_CODE       VARCHAR2(30)  NOT NULL,
    ITEM_EDESC      VARCHAR2(1000) NOT NULL,
    ITEM_NDESC      VARCHAR2(100),
    CATEGORY_CODE   VARCHAR2(30),
    PURCHASE_PRICE  NUMBER(18, 2),
    SALES_PRICE     NUMBER(18, 2),
    CURRENT_STOCK   NUMBER(18, 2),
    DELETED_FLAG    CHAR(1) DEFAULT 'N',
    CREATED_DATE    DATE DEFAULT SYSDATE,
    CONSTRAINT PK_IP_ITEM_MASTER PRIMARY KEY (COMPANY_CODE, ITEM_CODE)
);

CREATE TABLE SA_SALES_ORDER (
    COMPANY_CODE       VARCHAR2(30) NOT NULL,
    FORM_CODE          VARCHAR2(10) NOT NULL,
    ORDER_NO           VARCHAR2(20) NOT NULL,
    SERIAL_NO          NUMBER NOT NULL,
    ORDER_DATE         DATE NOT NULL,
    MANUAL_NO          VARCHAR2(20),
    CUSTOMER_CODE      VARCHAR2(30) NOT NULL,
    ITEM_CODE          VARCHAR2(30) NOT NULL,
    MU_CODE            VARCHAR2(5) DEFAULT 'PCS',
    QUANTITY           NUMBER(18, 2) NOT NULL,
    UNIT_PRICE         NUMBER(18, 2),
    TOTAL_PRICE        NUMBER(18, 2),
    CALC_QUANTITY      NUMBER(18, 2),
    CALC_UNIT_PRICE    NUMBER(18, 2),
    CALC_TOTAL_PRICE   NUMBER(18, 2),
    BRANCH_CODE        VARCHAR2(30) NOT NULL,
    CREATED_BY         VARCHAR2(30),
    CREATED_DATE       DATE DEFAULT SYSDATE,
    DELETED_FLAG       CHAR(1) DEFAULT 'N',
    DELIVERY_DATE      DATE,
    CANCEL_FLAG        CHAR(1) DEFAULT 'N',
    PAYMENT_MODE       VARCHAR2(30),
    DESCRIPTION        VARCHAR2(200),
    CONSTRAINT PK_SA_SALES_ORDER
        PRIMARY KEY (COMPANY_CODE, FORM_CODE, ORDER_NO, SERIAL_NO)
);

INSERT INTO SC_APPLICATION_USERS
    (USER_NO, COMPANY_CODE, LOGIN_CODE, LOGIN_EDESC, PASSWORD, CREATED_BY, DELETED_FLAG)
VALUES
    ('1', '01', 'suyog', 'Suyog', 'Test@123', 'seed', 'N');

INSERT INTO SC_APPLICATION_USERS
    (USER_NO, COMPANY_CODE, LOGIN_CODE, LOGIN_EDESC, PASSWORD, CREATED_BY, DELETED_FLAG)
VALUES
    ('2', '01', 'demo', 'Demo User', 'demo', 'seed', 'N');

INSERT INTO IP_ITEM_MASTER_SETUP
    (COMPANY_CODE, ITEM_CODE, ITEM_EDESC, CATEGORY_CODE,
     PURCHASE_PRICE, SALES_PRICE, CURRENT_STOCK, DELETED_FLAG)
VALUES
    ('01', 'LAPTOP001', 'Business Laptop 14 inch', 'ELECTRONICS',
     850, 1200, 25, 'N');

INSERT INTO IP_ITEM_MASTER_SETUP
    (COMPANY_CODE, ITEM_CODE, ITEM_EDESC, CATEGORY_CODE,
     PURCHASE_PRICE, SALES_PRICE, CURRENT_STOCK, DELETED_FLAG)
VALUES
    ('01', 'MONITOR001', '24 Inch LED Monitor', 'ELECTRONICS',
     140, 220, 40, 'N');

INSERT INTO IP_ITEM_MASTER_SETUP
    (COMPANY_CODE, ITEM_CODE, ITEM_EDESC, CATEGORY_CODE,
     PURCHASE_PRICE, SALES_PRICE, CURRENT_STOCK, DELETED_FLAG)
VALUES
    ('01', 'MOUSE001', 'Wireless Mouse', 'ACCESSORIES',
     12, 25, 100, 'N');

INSERT INTO IP_ITEM_MASTER_SETUP
    (COMPANY_CODE, ITEM_CODE, ITEM_EDESC, CATEGORY_CODE,
     PURCHASE_PRICE, SALES_PRICE, CURRENT_STOCK, DELETED_FLAG)
VALUES
    ('01', 'KEYBOARD001', 'Mechanical Keyboard', 'ACCESSORIES',
     35, 75, 60, 'N');

INSERT INTO IP_ITEM_MASTER_SETUP
    (COMPANY_CODE, ITEM_CODE, ITEM_EDESC, CATEGORY_CODE,
     PURCHASE_PRICE, SALES_PRICE, CURRENT_STOCK, DELETED_FLAG)
VALUES
    ('01', 'CHAIR001', 'Ergonomic Office Chair', 'FURNITURE',
     110, 180, 18, 'N');

INSERT INTO SA_SALES_ORDER
    (COMPANY_CODE, FORM_CODE, ORDER_NO, SERIAL_NO, ORDER_DATE,
     CUSTOMER_CODE, ITEM_CODE, MU_CODE, QUANTITY, UNIT_PRICE,
     TOTAL_PRICE, CALC_QUANTITY, CALC_UNIT_PRICE, CALC_TOTAL_PRICE,
     BRANCH_CODE, CREATED_BY, DELETED_FLAG, PAYMENT_MODE)
VALUES
    ('01', 'SO', 'ORD1001', 1, DATE '2025-07-17',
     'CUST001', 'LAPTOP001', 'PCS', 2, 1200,
     2400, 2, 1200, 2400, '01.01', 'demo', 'N', 'CREDIT');

INSERT INTO SA_SALES_ORDER
    (COMPANY_CODE, FORM_CODE, ORDER_NO, SERIAL_NO, ORDER_DATE,
     CUSTOMER_CODE, ITEM_CODE, MU_CODE, QUANTITY, UNIT_PRICE,
     TOTAL_PRICE, CALC_QUANTITY, CALC_UNIT_PRICE, CALC_TOTAL_PRICE,
     BRANCH_CODE, CREATED_BY, DELETED_FLAG, PAYMENT_MODE)
VALUES
    ('01', 'SO', 'ORD1001', 2, DATE '2025-07-17',
     'CUST001', 'MOUSE001', 'PCS', 2, 25,
     50, 2, 25, 50, '01.01', 'demo', 'N', 'CREDIT');

INSERT INTO SA_SALES_ORDER
    (COMPANY_CODE, FORM_CODE, ORDER_NO, SERIAL_NO, ORDER_DATE,
     CUSTOMER_CODE, ITEM_CODE, MU_CODE, QUANTITY, UNIT_PRICE,
     TOTAL_PRICE, CALC_QUANTITY, CALC_UNIT_PRICE, CALC_TOTAL_PRICE,
     BRANCH_CODE, CREATED_BY, DELETED_FLAG, PAYMENT_MODE)
VALUES
    ('01', 'SO', 'ORD1002', 1, DATE '2025-07-20',
     'CUST002', 'MONITOR001', 'PCS', 3, 220,
     660, 3, 220, 660, '01.02', 'demo', 'N', 'CASH');

INSERT INTO SA_SALES_ORDER
    (COMPANY_CODE, FORM_CODE, ORDER_NO, SERIAL_NO, ORDER_DATE,
     CUSTOMER_CODE, ITEM_CODE, MU_CODE, QUANTITY, UNIT_PRICE,
     TOTAL_PRICE, CALC_QUANTITY, CALC_UNIT_PRICE, CALC_TOTAL_PRICE,
     BRANCH_CODE, CREATED_BY, DELETED_FLAG, PAYMENT_MODE)
VALUES
    ('01', 'SO', 'ORD1003', 1, DATE '2025-08-05',
     'CUST003', 'KEYBOARD001', 'PCS', 5, 75,
     375, 5, 75, 375, '01.03', 'demo', 'N', 'CASH');

INSERT INTO SA_SALES_ORDER
    (COMPANY_CODE, FORM_CODE, ORDER_NO, SERIAL_NO, ORDER_DATE,
     CUSTOMER_CODE, ITEM_CODE, MU_CODE, QUANTITY, UNIT_PRICE,
     TOTAL_PRICE, CALC_QUANTITY, CALC_UNIT_PRICE, CALC_TOTAL_PRICE,
     BRANCH_CODE, CREATED_BY, DELETED_FLAG, PAYMENT_MODE)
VALUES
    ('01', 'SO', 'ORD1004', 1, DATE '2026-01-15',
     'CUST001', 'CHAIR001', 'PCS', 4, 180,
     720, 4, 180, 720, '01.02', 'demo', 'N', 'CREDIT');

COMMIT;

PROMPT Core demo tables created and seeded.
SELECT 'SC_APPLICATION_USERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SC_APPLICATION_USERS;

SELECT 'IP_ITEM_MASTER_SETUP' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM IP_ITEM_MASTER_SETUP;

SELECT 'SA_SALES_ORDER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM SA_SALES_ORDER;

EXIT;
